version: '3.8'

services:
  app:
    build: .
    container_name: story-service
    ports:
      - "${STORY_SERVICE_PORT}:${STORY_CONTAINER_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres_db
    networks:
      - backend

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres_db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
